name: Update GitHub Profile README

on:
  workflow_dispatch:  # Menjalankan secara manual

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate README dengan GitHub Profile Stats
      - name: Generate README with GitHub Profile Stats
        uses: anuraghazra/github-readme-stats@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          show_icons: true
          hide_title: false
          theme: dark

      # Commit dan Push jika ada perubahan
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Automated update of GitHub Profile README" || echo "No changes to commit"
          git push
